// Every player-visible string lives here (pt-BR).
export const STR = {
  title: "Hora de Aventura",
  subtitle: "Terra de Ooo",
  loading: "Carregando a Terra de Ooo…",
  play: "Jogar",
  resume: "Continuar",
  newGame: "Novo jogo",
  confirmNew: "Tem certeza? Clique de novo para apagar o progresso.",
  sound: "Som",
  shake: "Tremer a tela",
  bigText: "Texto grande",
  sens: "Sensibilidade da câmera",
  sensMouse: "Mouse e toque",
  sensPad: "Controle",
  paused: "Pausado",
  talkTo: "Conversar com",
  next: "E / Espaço para continuar",
  nextTouch: "Toque em Falar para continuar",
  lockHint: "Clique na tela para controlar a câmera com o mouse",
  ladderHint: "Na escada: W / ↑ sobe, S / ↓ desce, Espaço solta.",
  ladderHintTouch: "Na escada: empurre para cima para subir, para baixo para descer. Pular solta.",
  jump: "Pular",
  attack: "Espada",
  talk: "Falar",
  jakeBtn: "Jake",
  jakePower: "Punho gigante do Jake",
  fireBtn: "Fogo",
  firePower: "Onda de Fogo do Finn",
  combatHint: "Quando a gosma se encolhe e fica vermelha, ela vai pular em você: acerte antes ou saia da frente! Aperte <b>Q</b> para o <b>punho gigante</b> do Jake.",
  combatHintTouch: "Quando a gosma se encolhe e fica vermelha, ela vai pular em você: acerte antes ou saia da frente! Toque em <b>Jake</b> para o <b>punho gigante</b>.",
  found: (n, t) => `Cristal encontrado! <b>${n}/${t}</b>`,
  allFound: "Você achou TODOS os cristais de Ooo! Que aventura matemática!",
  fainted: "Você desmaiou… De volta à Casa da Árvore!",
  lava: "Ai! A lava queima!",
  controlsKeys: `
    <div><kbd>W A S D</kbd> ou setas — andar &nbsp; <kbd>Shift</kbd> — correr</div>
    <div><kbd>Espaço</kbd> — pular (aperte de novo no ar para o <b>pulo duplo</b>)</div>
    <div><kbd>J</kbd> ou clique — espada (aperte seguido: <b>combo</b>; no ar: <b>giro</b>) &nbsp; <kbd>E</kbd> — conversar</div>
    <div><kbd>Q</kbd> — <b>punho gigante</b> do Jake (e ele soca sozinho as gosmas por perto)</div>{FIRE}
    <div>Escadas: ande até elas e use <kbd>W</kbd> / <kbd>S</kbd></div>
    <div>Mouse — girar a câmera &nbsp; Roda — zoom &nbsp; <kbd>Esc</kbd> — pausar</div>
    <div>Controle: analógicos, <kbd>A</kbd> pular, <kbd>X</kbd> espada, <kbd>B</kbd> Jake, <kbd>Y</kbd> falar, <kbd>RT</kbd> correr</div>
    <div style="margin-top:6px">🎯 Encontre os <b>{N} cristais</b> escondidos em Ooo. Converse com o BMO, as princesas, a Marceline e o Rei Gelado: eles contam onde estão, e as pistas ficam anotadas aqui no menu (<kbd>Esc</kbd>). Entre nas casas e castelos: dá pra explorar por dentro!</div>`,
  controlsTouch: `
    <div>Lado esquerdo da tela — andar (empurre até o fim para correr)</div>
    <div>Lado direito — arrastar para girar a câmera</div>
    <div>Botões: <b>Pular</b> (toque de novo no ar para o pulo duplo), <b>Espada</b> (toque seguido para o combo; no ar, giro), <b>Jake</b> (punho gigante){FIRE}, <b>Falar</b></div>
    <div style="margin-top:6px">🎯 Encontre os <b>{N} cristais</b> escondidos em Ooo. Converse com o BMO, as princesas, a Marceline e o Rei Gelado: eles contam onde estão, e as pistas ficam anotadas aqui no menu (botão II). Entre nas casas e castelos: dá pra explorar por dentro!</div>`,
  // {FIRE} above, once the Flame Heart gave Finn the Fire Wave
  controlsFire: `
    <div><kbd>F</kbd> — <b>Onda de Fogo</b>: um golpe de espada que manda fogo pelo chão até o inimigo (controle: <kbd>RB</kbd>)</div>`,
  controlsFireTouch: ", <b>Fogo</b> (Onda de Fogo)",
  // the clue journal (pause menu) and the toast when someone gives one away
  cluesTitle: "Pistas",
  cluesNone: "Nenhuma pista ainda. Converse com o BMO, as princesas, a Marceline e o Rei Gelado: eles sabem onde estão os cristais.",
  cluesMore: "Tem mais cristal por aí que ninguém te contou ainda. Pergunte pro Jake quem pode saber!",
  clueNew: (n) => (n === 1 ? "📜 Pista anotada! Veja no menu (Esc)." : `📜 ${n} pistas anotadas! Veja no menu (Esc).`),
  clueNewTouch: (n) => (n === 1 ? "📜 Pista anotada! Veja no menu (II)." : `📜 ${n} pistas anotadas! Veja no menu (II).`),
  // who told where each treasure is (their line in `dialog` carries c: [ids]), as the journal writes it
  clues: {
    rock: ["bmo", "Em cima da pedra grande, na frente da Casa da Árvore."],
    treasureroom: ["bmo", "Na sala do tesouro da Casa da Árvore, lá embaixo, em cima da maior pilha de ouro."],
    bedroom: ["bmo", "Na gaveta onde o Jake dorme, no quarto da Casa da Árvore."],
    boat: ["bmo", "No barco-mirante no topo da árvore: saia pelo sótão e siga o galho."],
    armory: ["bmo", "No sótão da Casa da Árvore (a sala de armas), em cima do armário alto."],
    throne: ["pb", "No salão do trono do Castelo Doce, em cima do coração do trono."],
    candy: ["pb", "No alto da torre do Castelo Doce, perto da coroa de cerejas."],
    cupcake: ["pb", "No cupcake gigante, a sudeste do Reino Doce."],
    icecastle: ["iceking", "Na boca da montanha do Rei Gelado. Suba pelos degraus de gelo."],
    icepillars: ["iceking", "Nos pilares congelados, a sudoeste do castelo do Rei Gelado."],
    iceshelf: ["iceking", "Dentro do castelo do Rei Gelado, em cima da estante (suba pelos cubos de gelo)."],
    firelantern: ["flame", "Em cima da lanterna gigante do Rei de Fogo, na sala do trono do Palácio de Fogo."],
    firetower: ["flame", "No alto da torre do Palácio de Fogo, subindo pelas chaminés."],
    lava: ["flame", "No meio do lago de lava a noroeste do Palácio de Fogo, sobre as colunas de pedra."],
    marcy: ["marceline", "No telhado da casa da Marceline, na caverna."],
    marcyroom: ["marceline", "No quarto da Marceline, em cima do amplificador."],
    lumpy: ["lsp", "Na ilha da casa da Princesa Caroçuda, no Espaço Caroçudo."],
    lumpyparty: ["lsp", "Em cima das caixas de som do DJ, na festa da cúpula rosa do Espaço Caroçudo."],
  },
  // the ones who know, as a sentence names them, and where Jake says to find them
  npcThe: { bmo: "o BMO", pb: "a Princesa Jujuba", iceking: "o Rei Gelado", flame: "a Princesa de Fogo", marceline: "a Marceline", lsp: "a Princesa Caroçuda" },
  npcWhere: {
    bmo: "lá na Casa da Árvore",
    pb: "no salão do trono do Castelo Doce",
    iceking: "na frente do castelo dele, no Reino Gelado",
    icecrown: "lá na Coroa de Gelo, no topo da montanha dele",
    flame: "na sala do trono do Palácio de Fogo",
    marceline: "na caverna dela, a oeste",
    lsp: "no Espaço Caroçudo. A Marceline sabe o caminho",
  },
  areas: {
    fort: "Casa da Árvore",
    candycastle: "Castelo Doce",
    icecastle: "Castelo do Rei Gelado",
    icetop: "Coroa de Gelo",
    marcyhouse: "Casa da Marceline",
    firecastle: "Palácio de Fogo",
    grass: "Campos Verdes",
    candy: "Reino Doce",
    ice: "Reino Gelado",
    fire: "Reino do Fogo",
    dark: "Caverna da Marceline",
    sky: "Espaço Caroçudo",
    lair: "Covil das Trevas",
    colosseum: "Coliseu das Chamas",
    temple: "Templo do Enchiridion",
    lichcave: "Caverna dos Ossos",
  },
  // the minimap's compass
  compass: { n: "N", s: "S", e: "L", w: "O" },
  // text painted on signs in the world
  signs: { candy: "Reino Doce", ice: "Reino Gelado", fire: "Reino do Fogo", marcy: "Caverna da Marceline" },
  names: {
    jake: "Jake",
    bmo: "BMO",
    pb: "Princesa Jujuba",
    iceking: "Rei Gelado",
    gunter: "Gunter",
    flame: "Princesa de Fogo",
    marceline: "Marceline",
    lsp: "Princesa Caroçuda",
    banana: "Guarda Banana",
    pepbut: "Mordomo Menta",
    flameKing: "Rei de Fogo",
    billy: "Billy",
    lich: "Lich",
    lichEcho: "Eco do Lich",
  },
  dialog: {
    bmo: [
      "Oi, Finn! BMO está cuidando da casa!",
      { t: "Lá fora, bem na frente de casa, tem um cristal em cima da pedra grande. Esse é fácil!", c: ["rock"] },
      { t: "Tem cristal na sala do tesouro, lá embaixo — em cima da maior pilha de ouro!", c: ["treasureroom"] },
      { t: "E o Jake escondeu um na gaveta onde ele dorme, no quarto. Suba a escada ali no canto.", c: ["bedroom"] },
      { t: "Do sótão dá pra sair no topo da árvore. Siga o galho até o barco-mirante: tem cristal lá!", c: ["boat"] },
      { t: "E no sótão, que agora é a sala de armas, tem um cristal em cima do armário alto. É só pular!", c: ["armory"] },
    ],
    pb: [
      "Finn! Bem-vindo ao meu salão do trono.",
      { t: "Tem um cristal bem aqui, em cima do coração do meu trono. Suba pela jujuba azul e dê um pulo duplo!", c: ["throne"] },
      { t: "Escondi outro no alto da torre do castelo, perto da coroa de cerejas. Suba pelas jujubas lá fora e pelas nuvens de algodão-doce.", c: ["candy"] },
      { t: "E tem mais um no cupcake gigante, a sudeste do reino. Ah, e não mexa no meu laboratório, tá?", c: ["cupcake"] },
    ],
    pepbut: [
      "Seja bem-vindo ao Castelo Doce, senhor Finn.",
      "A princesa está no fundo do salão, ao lado do trono.",
      "Por favor, não coma a mobília. De novo.",
    ],
    // (his quest and the fight in the Dark Lair: STR.mint)
    banana: [
      "Alto lá! …Ah, é você, Finn. Pode passar.",
      "A princesa está no salão do trono. É só entrar pela porta grande do castelo.",
    ],
    iceking: [
      "Hã?! Finn! Veio roubar minhas princesas? …Ah, veio pelos cristais.",
      { t: "Tem um cristal na boca da minha montanha — é, a montanha tem cara! Suba pelos degraus de gelo.", c: ["icecastle"] },
      { t: "E o Gunter escondeu outro nos pilares congelados a sudoeste daqui.", c: ["icepillars"] },
      { t: "E NÃO entre no meu castelo pela porta da frente! …Tá, entra. Mas não sobe nos cubos de gelo pra pegar o cristal de cima da minha estante!", c: ["iceshelf"] },
    ],
    gunter: ["Wenk.", "Wenk wenk!"],
    flame: [
      "Oi, Finn! Bem-vindo à minha sala do trono. Cuidado com a lava lá fora, ela queima de verdade!",
      { t: "Tem um cristal em cima da lanterna gigante do meu pai, bem ali. Suba no toco do lado e dê um pulo duplo.", c: ["firelantern"] },
      { t: "Outro está no alto da torre do palácio. Suba pelas chaminés, girando em volta dele.", c: ["firetower"] },
      { t: "E mais um no meio do lago de lava, a noroeste daqui. Pise nas colunas de pedra.", c: ["lava"] },
    ],
    marceline: [
      "E aí, Finn? Bem-vindo à minha caverna.",
      { t: "Deixei um cristal no telhado da minha casa. As caixas ajudam, mas o último pulo é duplo!", c: ["marcy"] },
      "Quer um desafio de verdade? Siga os cogumelos até as nuvens do Espaço Caroçudo.",
      { t: "Pode entrar em casa, a porta tá aberta. Tem mais um cristal lá em cima, no meu quarto, em cima do amplificador. Só não mexe no meu baixo!", c: ["marcyroom"] },
    ],
    lsp: [
      "Ai, meu Glob! Tipo, como você chegou aqui no Espaço Caroçudo?!",
      { t: "Tá, pode pegar o cristal aqui da ilha. Mas só porque você é, tipo, meio caroçudo também.", c: ["lumpy"] },
      { t: "E vai ter festa na cúpula rosa! Pula pelas nuvenzinhas até lá. Tem outro cristal em cima das caixas de som do DJ.", c: ["lumpyparty"] },
      "Ah, e o Ponto do Amasso é naquela ilha com o morro laranja. Nem pensa em ir lá comigo. Eca.",
    ],
    jakeNone: "Você achou tudo, mano! Agora é só curtir Ooo.",
    // Jake doesn't know where they are, only who to ask (or what you were told)
    jakeAsk: (name, where) => `Sei lá onde tem cristal, mano… mas aposto que ${name} sabe. Procura ${where}.`,
    jakeRemind: (name, clue) => `Lembra o que ${name} falou? ${clue}`,
    jakeExtra: ["Tô contigo, mano!", "Hora de aventura!"],
  },
  // the Candy People (and the Fire Kingdom's): a random line from their kind's list or their home's
  citizens: {
    names: {
      gumdrop: "Cidadão Jujuba", candycorn: "Milho Doce", marshmallow: "Marshmallow", jellybean: "Bala de Goma",
      cupcake: "Sr. Cupcake", cinnamon: "Pão de Canela", strawberry: "Morango", icecream: "Sorvetinho",
      flameling: "Cidadão de Fogo", coal: "Carvãozinho", guard: "Guarda de Fogo", lumpy: "Caroçudo",
    },
    lines: {
      gumdrop: ["Oi, Finn! Que dia doce, né?", "Cuidado pra não pisar em mim, eu sou pequenininho!"],
      candycorn: ["Dizem que eu sou o doce mais controverso de Ooo. Sei lá por quê.", "Viu a fonte de chocolate? Não pode beber, é decoração!"],
      marshmallow: ["Tô todo derretido de ver o herói de Ooo!", "Não chegue perto da lava, por favor. Eu tosto fácil."],
      jellybean: ["Pulei tanto hoje que tô todo mole!", "A Princesa Jujuba inventou um sabor novo ontem. Explodiu um pouco."],
      cupcake: ["Bom dia, jovem aventureiro. Belo chapéu.", "Meu bigode é de alcaçuz. Genuíno."],
      cinnamon: ["Finn! Finn! Eu sou seu fã número um!", "Eu ia ajudar a guarda, mas me distraí com uma borboleta."],
      strawberry: ["Olha o meu cabelo novo! São folhas.", "Os Guardiões de Chiclete estão de olho em tudo, sabia?"],
      icecream: ["Tá calor, tá calor… vou derreter!", "Me vê de longe? Eu sou o de cereja em cima."],
      flameling: ["Cuidado pra não encostar, eu queimo!", "Você não é de fogo? Que estranho… e molhadinho.", "A Princesa de Fogo mandou reforçar a guarda. Da lava, sei lá."],
      lumpy: ["Ai, meu Glob! Um não-caroçudo!", "Tipo, você vai na festa? Todo mundo vai estar lá.", "Nem vem, eu tô, tipo, super de boa.", "Os caroços são, tipo, a última moda. Óbvio."],
      guard: ["Alto! …Ah, o amigo da princesa. Pode passar.", "A sala do trono é logo ali dentro. Não toque na lanterna do rei!", "Eu vigio a porta há cem anos. É quentinho."],
      coal: ["Hoje eu tô meio apagado.", "Eu já fui uma árvore, sabia? Agora sou carvão. A vida é assim.", "Não me assopra que eu acendo!"],
    },
    // where each kind lives picks the lines everyone there says (default: candy)
    home: { flameling: "fire", coal: "fire", guard: "fire", lumpy: "lumpy" },
    common: {
      candy: ["Viva a Princesa Jujuba!", "Hora de aventura!", "Já foi no castelo? O salão do trono é lindo!"],
      fire: ["Viva a Princesa de Fogo!", "Hora de aventura! …Quentinha."],
      lumpy: ["Ai, meu Glob!", "Tipo, sério mesmo?", "Aquela festa vai ser, tipo, caroçudamente incrível."],
    },
  },
  // the Ice King's quest (quest.js) and his fight on the Ice Crown (boss.js)
  ice: {
    // what he says in his hall, by quest step
    offer: [
      "Hã?! Finn! Veio roubar minhas princesas? …Ah, veio pelos cristais.",
      "Escuta, eu tô com um probleminha. Meus pinguins fugiram! Cinco Gunters espalhados pelo Reino Gelado!",
      "Traz todos de volta pra mim e eu te dou… uma surpresa. Uma surpresa MUITO especial.",
      { t: "Ah, e se tá atrás de cristal: tem um na boca da minha montanha, um que o Gunter escondeu nos pilares congelados… e um na minha estante. NÃO pega esse!", c: ["icecastle", "icepillars", "iceshelf"] },
    ],
    // before Billy sends Finn after the crystals (billy.js): he won't tell just anyone
    locked: [
      "Hã?! Finn! Veio roubar minhas princesas? …Ah, veio pelos cristais.",
      "Olha, eu tô com um probleminha. Mas não conto pra qualquer um, só pra herói de verdade!",
      "Vai falar com aquele velho barbudo, o Billy, lá na sua casa. Se ele disser que você é herói, aí eu conto. …Que barba bonita a dele, hein? Quase tão bonita quanto a minha.",
      { t: "Ah, e se tá atrás de cristal: tem um na boca da minha montanha, um que o Gunter escondeu nos pilares congelados… e um na minha estante. NÃO pega esse!", c: ["icecastle", "icepillars", "iceshelf"] },
    ],
    progress: (n) => (n === 1 ? "Cadê o último Gunter? Falta só um!" : `Cadê meus Gunters? Ainda faltam ${n}!`),
    pengHint: "Vi um subindo a minha montanha, outro em cima de um cubo lá nos pilares congelados… os outros fugiram pros lados e pra trás da montanha.",
    challenge: [
      "MEUS GUNTERS! Todos de volta! Ai, que saudade de vocês.",
      "E agora a surpresa, Finn: você vive estragando meus casamentos com as princesas!",
      "Hoje isso acaba! Te espero na Coroa de Gelo, lá no topo da minha montanha. Um duelo de verdade!",
    ],
    // at the Ice Crown after he loses (talking starts a rematch)
    rest: [
      "Tá, tá, você venceu… Minha barba ainda tá doendo.",
      { t: "Ainda atrás de cristal? Tem um na boca da minha montanha, um nos pilares congelados e um na estante do meu castelo. Pronto, falei.", c: ["icecastle", "icepillars", "iceshelf"] },
      "Quer revanche? Então prepara essa espadinha!",
    ],
    // quest progress (toasts and the objective box)
    accepted: "Missão: resgate os <b>5 pinguins</b> do Rei Gelado. Siga os feixes azuis!",
    rescued: (n, t) => `Pinguim resgatado! <b>${n}/${t}</b>`,
    allRescued: "Todos os pinguins! Volte ao castelo do Rei Gelado.",
    flewOff: "O Rei Gelado voou para a <b>Coroa de Gelo</b>, no topo da montanha!",
    goalPengs: (n, t) => `Pinguins do Rei Gelado: ${n}/${t}`,
    goalBack: "Volte ao Rei Gelado",
    goalCrown: "Suba até a Coroa de Gelo",
    // the fight
    near: "Aí está você! Entra, se tiver coragem!",
    intro: "Bem-vindo à Coroa de Gelo, Finn! Agora você vai sentir o poder do Rei Gelado!",
    cast: { bolt: "Raio de Gelo", breath: "Sopro Congelante", nova: "Explosão Glacial", donut: "Anel de Nevasca", dive: "Mergulho da Barba" },
    shout: {
      bolt: ["Raio de gelo! Dança, garoto!", "Chuva de raios! Congela!"],
      breath: ["Sopro congelante! Hahh!", "Sente o meu bafo gelado!"],
      nova: ["Pra trás, plebeu! Explosão glacial!", "Sai de perto de mim!"],
      donut: ["Vem cá me dar um abraço… de gelo!", "Anel de nevasca! Ninguém escapa!"],
      dive: ["Mergulho da barba!", "Lá vou eu! Olha a sombra!"],
    },
    dazed: ["Ai… minha coluna…", "Tô vendo pinguins…"],
    dropped: ["Ei! Esse coração era meu!", "Meu coraçãozinho gelado!", "Devolve isso!"],
    healHint: "Na luta você <b>não se cura sozinho</b>: pegue os corações que o Rei Gelado deixa cair quando apanha!",
    hurt: ["Ai! Minha barba!", "Isso não vale!", "Gunter, me ajuda!", "Ai, ai, ai!", "Na coroa não!"],
    phase2: "Agora eu fiquei BRAVO! Minha coroa tá fervendo… de frio!",
    phase3: "Chega! Todos os poderes de uma vez!",
    finnDown: "Ha! Viu só? Ninguém vence o Rei Gelado!",
    defeat: "Aaai! Minha coroa! Tá bom, tá bom… você venceu!",
    phase: ["", "Bravo!", "Fúria total!"],
    // the reward
    heart: "Você ganhou o <b>Coração de Gelo</b> e o <b>Diamante de Gelo</b>! Agora são 6 corações.",
    healed: "Vitória! Corações cheios.",
    faint: "Você desmaiou… Tente de novo! O Rei Gelado te espera.",
  },
  // the Peppermint Butler's quest (spirits.js) and his fight in the Dark Lair (butler.js)
  mint: {
    // what he says in the castle, by quest step
    offer: [
      "Ah, senhor Finn. Que bom que chegou. Tenho um… pequeno problema doméstico.",
      "Eu estava lendo meu grimório. O proibido. E cinco espíritos escaparam das páginas! Estão soltos pelo Reino Doce.",
      "Se a princesa descobrir, vou ter que esfregar o castelo inteiro com uma escova de dente. De novo.",
      "Traga os espíritos de volta. É só encostar neles, o frasco que eu lhe dei faz o resto. Em troca… uma recompensa à altura de um herói.",
    ],
    // before Finn has the Ice Crystal (crystals.js): he won't trust him with the grimoire yet
    locked: [
      "Ah, senhor Finn. Seja bem-vindo ao Castelo Doce.",
      "Tenho um assunto… delicado. Do tipo que eu só confio a um herói de verdade.",
      "Dizem que o Rei Gelado anda desafiando quem aparece no Reino Gelado. Vença-o e traga o Diamante de Gelo como prova. Aí conversaremos.",
    ],
    progress: (n) => (n === 1 ? "Falta só um espírito, senhor Finn. Consigo ouvi-lo gemendo em algum lugar…" : `Ainda faltam ${n} espíritos, senhor Finn. Eles adoram lugares altos, escuros e… doces.`),
    hint: "Um foi para o laboratório da princesa, outro subiu no telhado dele. Vi um na praça da fonte, um atrás do castelo e outro lá no cupcake gigante.",
    challenge: [
      "Os cinco! Esplêndido, senhor Finn. Estão todos de volta ao grimório.",
      "Agora, a recompensa: forjei uma espada para o senhor. Mas uma lâmina das trevas só obedece a quem vence o seu ferreiro.",
      "Então terei que testá-lo pessoalmente. No meu covil, onde ninguém nos incomoda. Segure-se no cachorro.",
    ],
    retry: [
      "Mortais… tão frágeis. Já se recuperou, senhor Finn?",
      "Muito bem. De volta ao covil. Segure-se.",
    ],
    after: [
      "A Espada da Noite lhe caiu muito bem, senhor Finn. Ela corta até fantasma.",
      "Não conte à princesa sobre o covil. Nem sobre o grimório. Nem sobre… bem, sobre nada.",
      "Se quiser treinar de novo, é só falar comigo outra vez.",
    ],
    rematch: [
      "Revanche? Que delícia. Quero dizer: como quiser, senhor Finn.",
      "Segure-se.",
    ],
    // the quest's toasts and the objective box
    accepted: "Missão: devolva os <b>5 espíritos</b> do Mordomo Menta. Siga os feixes roxos pelo Reino Doce!",
    caught: (n, t) => `Espírito capturado! <b>${n}/${t}</b>`,
    allCaught: "Todos os espíritos! Volte ao Mordomo Menta, no Castelo Doce.",
    goalSpirits: (n, t) => `Espíritos do Mordomo: ${n}/${t}`,
    goalBack: "Volte ao Mordomo Menta",
    // the fight
    intro: "Bem-vindo ao Covil das Trevas, senhor Finn. Limpe os pés antes de entrar… na sua ruína.",
    cast: { stakes: "Chuva de Estacas", hands: "Mãos do Além", hiss: "Sibilo Sombrio", summon: "Invocar Diabinhos", shadow: "Passo Sombrio", seal: "Selo Sombrio", armor: "Armadura Astral", slam: "Golpe Astral" },
    shout: {
      stakes: ["Meu kit de caçar vampiros! Com licença…", "Estacas, direto do porão!"],
      hands: ["Mãos do Além! Elas adoram visitas.", "Os mortos querem um aperto de mão!"],
      hiss: ["Hsssss!", "Chega perto que eu… HSSS!"],
      summon: ["Venham, meus diabinhos! Hora do lanche!", "Crianças, cumprimentem o senhor Finn!"],
      shadow: ["Onde será que eu fui parar?", "Atrás de você. Na sua sombra."],
      seal: ["Selo Sombrio! Só a luz abençoada vai te salvar.", "Corra para a luz, senhor Finn!"],
      armor: ["Contemplem a minha Armadura Astral!", "Meu corpo espiritual, com espada flamejante e tudo!"],
      repel: ["Tire as mãos do meu fraque!", "Chega de cutucar!", "Afaste-se, plebeu!"],
    },
    dazed: ["Ufa… magia cansa…", "Um momento… preciso de um chá."],
    dropped: ["Isso era da despensa da princesa!", "Opa, meu doce!", "Devolva, por favor."],
    hurt: ["Que falta de modos!", "Ai! Meu fraque!", "Isso vai manchar!", "Ui, na hortelã não!", "Senhor Finn, francamente!"],
    phase2: "Chega de gentileza. Agora vocês vão conhecer o Sombrio!",
    phase3: "Pelas trevas da Noitosfera! Armadura Astral, desperte!",
    finnDown: "Hmph. Descanse, senhor Finn. Eu o levo de volta ao castelo.",
    defeat: "Impressionante… Muito impressionante, senhor Finn. O senhor venceu.",
    gift: "A Espada da Noite é sua, senhor Finn. Pegue-a… e saia pelo portal.",
    again: "Excelente treino, senhor Finn. O portal está aberto.",
    phase: ["", "Sombrio!", "Armadura Astral!"],
    healHint: "Aqui você também <b>não se cura sozinho</b>: pegue os corações que o Mordomo Menta deixa cair. Um golpe de espada acaba com cada diabinho!",
    faint: "Você desmaiou… O Mordomo Menta te levou de volta ao castelo.",
    portal: "Um <b>portal</b> se abriu na beira do covil: entre nele para voltar ao Reino Doce.",
    sword: "Você ganhou a <b>Espada da Noite</b> e o <b>Diamante da Noite</b>! A espada causa o dobro de dano e alcança mais longe.",
    healed: "Vitória! Corações cheios.",
  },
  // Flame Princess's quest, the Path of Flames (flamepath.js), and her father's fight in the Colosseum of Flames (flameking.js)
  fire: {
    // what she says in her throne room, by quest step
    offer: [
      "Finn! Que bom que você veio. Eu tenho um problema… e ele se chama papai.",
      "Pela lei antiga do fogo, um rei deposto pode desafiar a coroa para um duelo no Coliseu das Chamas. E o meu pai desafiou, lá de dentro da lanterna!",
      "Se eu lutar e perder a cabeça, queimo o reino inteiro. Eu preciso de um campeão. Você, Finn!",
      "Só que o coliseu só se abre quando o campeão acende o Caminho das Chamas: cinco braseiros, um depois do outro, com a Chama Real.",
      "Toma, ela é sua. Mas você é molhado, então ela apaga rapidinho! Corra de um braseiro pro outro. Se ela apagar, o último braseiro aceso reacende.",
      { t: "Ah, e se tá atrás de cristal: tem um em cima da lanterna do meu pai, aqui do lado, um no alto da torre do palácio e um no meio do lago de lava a noroeste.", c: ["firelantern", "firetower", "lava"] },
    ],
    // before Finn has the Night Crystal (crystals.js): her father would burn a rookie to a crisp
    locked: [
      "Oi, Finn! Bem-vindo à minha sala do trono. Cuidado com a lava lá fora, ela queima de verdade!",
      "Eu tenho um problema sério… mas preciso de um campeão que já tenha enfrentado as trevas.",
      "Dizem que o Mordomo Menta, lá do Castelo Doce, esconde um covil sombrio. Vença ele e traga o Diamante da Noite. Aí a gente conversa.",
      { t: "Ah, e se tá atrás de cristal: tem um em cima da lanterna do meu pai, aqui do lado, um no alto da torre do palácio e um no meio do lago de lava a noroeste.", c: ["firelantern", "firetower", "lava"] },
    ],
    progress: (n) => (n === 1 ? "Falta só um braseiro, Finn! O do alto da torre." : `Ainda faltam ${n} braseiros do Caminho das Chamas, Finn.`),
    // where the next brazier is (by how many are already lit)
    where: [
      "O primeiro braseiro fica lá fora, do lado da porta do palácio.",
      "O segundo fica na vila, a leste do palácio, entre as casinhas.",
      "O terceiro também fica na vila, do outro lado: ao sul, atrás do palácio.",
      "O quarto está no meio da subida das chaminés, em volta do palácio. Pule de toco em toco!",
      "O último fica no alto da torre do palácio, no fim da subida das chaminés.",
    ],
    challenge: [
      "O Caminho das Chamas está aceso! Você é demais, Finn.",
      "O coliseu se abriu. Meu pai já está lá, esperando por você.",
      "Ele é enorme e joga fogo pra todo lado. E quando ele erguer o Sol do Rei, esconda-se atrás de uma coluna!",
      "Segurem firme, vocês dois. Lá vão vocês!",
    ],
    retry: [
      "Você tá bem, Finn? Meu pai é duro na queda.",
      "Lembra: pule as ondas de fogo e, quando ele erguer o Sol do Rei, atrás de uma coluna! De volta ao coliseu!",
    ],
    after: [
      "Você venceu meu pai, Finn! O reino inteiro só fala disso.",
      "Ele voltou pra lanterna resmungando. Mas acho que, lá no fundo, ficou orgulhoso.",
      { t: "E se ainda tá atrás de cristal: tem um em cima da lanterna dele, um no alto da torre do palácio e um no lago de lava a noroeste.", c: ["firelantern", "firetower", "lava"] },
      "Se quiser outro duelo, é só falar comigo de novo.",
    ],
    rematch: [
      "Outro duelo? Meu pai vai adorar. Quer dizer… odiar.",
      "Lá vão vocês!",
    ],
    // the quest's toasts and the objective box
    accepted: "Missão: acenda o <b>Caminho das Chamas</b>: 5 braseiros, em ordem, antes que a Chama Real se apague. Siga o feixe de fogo!",
    lit: (n, t) => `Braseiro aceso! <b>${n}/${t}</b> Corra para o próximo!`,
    allLit: "O <b>Caminho das Chamas</b> está aceso! Volte à Princesa de Fogo, no Palácio de Fogo.",
    outRelight: "A Chama Real se apagou! Volte ao <b>último braseiro aceso</b> para reacendê-la.",
    outFlame: "A Chama Real se apagou! Volte à <b>Princesa de Fogo</b> para pegar outra.",
    goalRun: (n, t, s) => `Caminho das Chamas ${n}/${t} · 🔥 ${s} s`,
    goalRelight: (n) => `Reacenda a chama no braseiro ${n}`,
    goalFlame: "Pegue a Chama Real com a Princesa de Fogo",
    goalBack: "Volte à Princesa de Fogo",
    // the fight
    intro: "Então a minha filha mandou um humano molhado lutar por ela? Que vergonha… Bem-vindo ao Coliseu das Chamas!",
    cast: { fireball: "Bolas de Fogo", meteor: "Chuva de Meteoros", pillars: "Pilares de Fogo", stomp: "Pisão Flamejante", slam: "Soco no Chão", charge: "Investida Real", leap: "Salto do Rei", sun: "Sol do Rei", counter: "Erupção" },
    shout: {
      fireball: ["Bolas de fogo! Pega essa!", "Toma, toma, TOMA!"],
      meteor: ["Que chova fogo!", "Olha pro céu, humano!"],
      pillars: ["Pilares de fogo! Dança pra mim!", "O chão é lava! Literalmente!"],
      stomp: ["Sente o peso de um rei!", "PISÃO!"],
      slam: ["Vou rachar esse chão com a sua cara!", "Soco real!"],
      charge: ["Sai da frente do rei!", "Lá vou eu!"],
      leap: ["Salto do rei! Olha a sombra!", "Lá de cima eu te amasso!"],
      sun: ["Contemplem o SOL DO REI!", "Queimem, todos vocês!"],
      counter: ["Tire suas mãos da minha armadura!", "Chega de cutucar!", "Pra trás, plebeu!"],
    },
    crash: ["AI! Quem colocou essa coluna aí?!", "Minha coroa… tá rodando…"],
    dazed: ["Ufa… esse cansa até um rei…", "Um momento… preciso de lenha."],
    dropped: ["Ei! Esse coração era do meu estoque!", "Devolve isso!", "Meu coraçãozinho quente!"],
    hurt: ["Insolente!", "Um rei não sente dor!", "Minha armadura!", "Você vai pagar por isso!", "Isso arde… digo, não arde!"],
    phase2: "Chega de brincadeira! Sintam o calor de um rei de verdade!",
    phase3: "Vocês me obrigaram! Contemplem… a CHAMA AZUL!",
    finnDown: "Ha! Volte pra casa, humano molhado. E diga pra minha filha que o trono é meu!",
    defeat: "Impossível… vencido por um humano… Tá bom, tá bom. Eu volto pra lanterna.",
    gift: "Você conseguiu, Finn! Pegue o Coração de Chama e saia pelo portão!",
    again: "Venceu de novo, Finn! O portão está aberto.",
    phase: ["", "Fúria!", "Chama Azul!"],
    healHint: "Aqui você também <b>não se cura sozinho</b>: pegue os corações que o Rei de Fogo deixa cair. E cuidado: <b>fogo no chão queima</b>, e as ondas de fogo você pula!",
    sunHint: "Esconda-se <b>atrás de uma coluna</b>: só a sombra dela protege do Sol do Rei!",
    faint: "Você desmaiou… A Princesa de Fogo te trouxe de volta ao palácio.",
    portal: "O <b>portão</b> do coliseu se abriu: entre nele para voltar ao Palácio de Fogo.",
    heart: "Você ganhou o <b>Coração de Chama</b> e o <b>Diamante de Fogo</b>! Mais um coração… e o poder do fogo: aperte <b>F</b> para a <b>Onda de Fogo</b>!",
    heartTouch: "Você ganhou o <b>Coração de Chama</b> e o <b>Diamante de Fogo</b>! Mais um coração… e o poder do fogo: toque em <b>Fogo</b> para a <b>Onda de Fogo</b>!",
    // a save from before the Fire Wave existed: the Flame Heart was already Finn's
    waveNew: "O <b>Coração de Chama</b> te deu um poder novo: aperte <b>F</b> para lançar a <b>Onda de Fogo</b> com a espada!",
    waveNewTouch: "O <b>Coração de Chama</b> te deu um poder novo: toque em <b>Fogo</b> para lançar a <b>Onda de Fogo</b> com a espada!",
    healed: "Vitória! Corações cheios.",
  },
  // the boss crystals (crystals.js): the HUD, the journal, and what to do next
  crystals: {
    title: "Diamantes",
    names: { ice: "Diamante de Gelo", mint: "Diamante da Noite", fire: "Diamante de Fogo" },
    from: { ice: "vença o Rei Gelado", mint: "vença o Mordomo Menta", fire: "vença o Rei de Fogo" },
    // the journal's next step, by how many Finn has (3: the temple; after the book: done)
    next: [
      "Fale com o Rei Gelado, no castelo dele, no Reino Gelado: ele guarda o primeiro diamante.",
      "Com o Diamante de Gelo, o Mordomo Menta, no Castelo Doce, vai confiar uma missão a você.",
      "Com o Diamante da Noite, a Princesa de Fogo, no Palácio de Fogo, vai aceitar você como campeão.",
      "Os três diamantes! Agora ache todos os cristais espalhados por Ooo e leve tudo ao Billy, na porta do Templo do Enchiridion, a leste da Casa da Árvore.",
      "O Enchiridion é seu. Você é o herói de Ooo!",
    ],
    // the toast after a crystal, a little after the prize's own
    got: [
      "",
      "O Diamante de Gelo brilha… Um templo antigo nos Campos Verdes, a leste da Casa da Árvore, tem <b>três encaixes</b> de diamante. E o <b>Mordomo Menta</b> quer falar com você.",
      "O Diamante da Noite se juntou ao de Gelo! Agora a <b>Princesa de Fogo</b> vai querer você como campeão.",
      "Os <b>três diamantes</b>! Agora é achar os <b>cristais</b> espalhados por Ooo e levar tudo ao <b>Billy</b>, na porta do <b>Templo do Enchiridion</b>.",
    ],
  },
  // the Temple of the Enchiridion (temple.js)
  temple: {
    billy: "Os diamantes e os cristais brilham na sua mochila… Fale com o <b>Billy</b>, aqui na frente do templo: ele sabe abrir a porta.",
    // what's missing: the diamonds' names and how many crystals are still out there
    need: (names, left) => `A porta do templo tem <b>três encaixes</b> de diamante e um arco de encaixes de cristal. Falta: ${[...names.map((n) => `<b>${n}</b>`), ...(left ? [`<b>${left} ${left > 1 ? "cristais" : "cristal"}</b>`] : [])].join(", ")}.`,
    open: "Os diamantes e os cristais se acendem… A porta do <b>Templo do Enchiridion</b> se abriu!",
    book: "Você pegou o <b>Enchiridion</b>, o livro dos heróis! Você é o <b>herói de Ooo</b>!",
    done: "Os três chefes vencidos e o Enchiridion nas mãos. Que aventura matemática!",
  },
  // Billy (billy.js): his test (five slimes), then the crystals for the temple door
  billy: {
    offer: [
      "Ora, ora… Finn, o humano, e Jake, o cão. Já ouvi falar muito de vocês dois.",
      "Eu sou o Billy. Há muito tempo, fui o maior herói de Ooo. Venci o Lich e o prendi no âmbar.",
      "Hoje estou velho… mas ainda sei reconhecer um herói de verdade quando vejo um.",
      "Antes de te confiar a missão mais importante de Ooo, quero ver essa espada em ação. Derrote 5 gosmas!",
      "Tem gosmas pelos Campos Verdes: a leste daqui, no caminho de um templo antigo, e mais longe para o norte e o sul. Vá, jovem herói!",
    ],
    progress: (n) => (n === 1 ? "Só mais uma gosma, jovem Finn! Estou vendo tudo daqui." : `Ainda faltam ${n} gosmas, Finn. Um herói não desiste no meio do caminho!`),
    hint: "Elas ficam pelos Campos Verdes: a leste daqui, no caminho do templo, e mais longe para o norte e o sul. O mapa mostra onde estão.",
    tip: "E lembre: pular em cima de uma gosma também vale!",
    // five slimes: the real quest (he leaps off to the temple after it)
    proud: [
      "Cinco gosmas! Você luta como eu na sua idade. Talvez até melhor.",
      "Agora escute bem. A leste daqui existe um templo antigo. Lá dentro está o Enchiridion, o livro dos heróis.",
      "A porta dele tem dois tipos de encaixe. Três são para os diamantes que os chefes de Ooo guardam.",
      "O primeiro diamante está com o Rei Gelado, no Reino Gelado, ao norte. Depois vem o Mordomo Menta, no Castelo Doce. E por fim, a Princesa de Fogo e o pai dela, no Reino do Fogo, ao sul.",
      "Os outros são para os cristais dourados espalhados por Ooo. Todos eles, Finn. Quem vive por aí sabe onde estão: pergunte ao BMO, às princesas, à Marceline… até ao Rei Gelado.",
      "Vou na frente e te espero na porta do templo. Traga os diamantes e os cristais, jovem herói!",
    ],
    // at the temple: the next diamond (by how many Finn has, 0..2), then how many crystals are left
    waiting: "Ah, jovem Finn! Continuo aqui, vigiando a porta.",
    where: [
      "O primeiro diamante está com o Rei Gelado. Fale com ele na frente do castelo dele, no Reino Gelado, ao norte.",
      "O Diamante de Gelo! Agora o Mordomo Menta, no salão do Castelo Doce, a leste, vai te confiar uma missão.",
      "Gelo e Noite! Falta o Diamante de Fogo: a Princesa de Fogo precisa de um campeão, no Palácio de Fogo, ao sul.",
      "Os três diamantes! Gelo, Noite e Fogo… Brilham como nos velhos tempos.",
    ],
    left: (n) => (n === 1 ? "E falta só um cristal! Pergunte ao Jake quem pode saber onde ele está." : `E ainda faltam ${n} cristais espalhados por Ooo. O Jake sabe quem pode te contar onde estão.`),
    allGems: "E todos os cristais de Ooo! Que jornada, Finn.",
    need: "Diamantes e cristais, Finn. Sem todos eles, nem eu consigo abrir essa porta.",
    ready: [
      "Os três diamantes… e todos os cristais de Ooo! Brilham como nos velhos tempos.",
      "Me dê aqui. Cada um no seu encaixe…",
      "A porta é sua, Finn. Lá dentro está o Enchiridion. Pegue-o: você mereceu.",
    ],
    after: ["Vá em frente, Finn. O Enchiridion está esperando por você lá dentro."],
    done: [
      "Você conseguiu, Finn. O Enchiridion escolheu você.",
      "Agora eu posso descansar… O herói de Ooo é você.",
      "Se um dia precisar de conselho, estarei aqui, olhando o horizonte.",
    ],
    // toasts and the objective box
    accepted: "Missão: derrote <b>5 gosmas</b> para o Billy ver sua espada em ação!",
    killed: (n, t) => `Gosma derrotada! <b>${n}/${t}</b>`,
    allKilled: "Cinco gosmas! Volte ao <b>Billy</b>, na frente da Casa da Árvore.",
    crystals: "Missão: vença os chefes pelos <b>3 diamantes</b>, ache <b>todos os cristais</b> de Ooo e leve tudo ao Billy, no <b>Templo do Enchiridion</b>. Comece pelo <b>Rei Gelado</b>, ao norte!",
    // the last crystal (or diamond) came in: off to Billy
    complete: "Os <b>três diamantes</b> e <b>todos os cristais</b>! Leve tudo ao <b>Billy</b>, na porta do <b>Templo do Enchiridion</b>.",
    leapt: "O Billy saltou para o <b>Templo do Enchiridion</b>, a leste da Casa da Árvore!",
    goalSlimes: (n, t) => `Gosmas para o Billy: ${n}/${t}`,
    goalBack: "Volte ao Billy, na Casa da Árvore",
    goalCrystals: (d, dt, g, gt) => `Para o Billy: 💎 ${d}/${dt} · cristais ${g}/${gt}`,
    goalTemple: "Leve tudo ao Billy, no Templo",
    // the journal's next step before the crystals
    next: {
      none: "Fale com o Billy, na frente da Casa da Árvore.",
      slimes: "Derrote 5 gosmas para o Billy ver sua espada em ação.",
      back: "Volte ao Billy, na frente da Casa da Árvore.",
    },
  },
  // the twist (lich.js): Billy was the Lich all along; his portal, his cave of bones
  lich: {
    // "Billy", by the temple door, once Finn walks out with the book
    ask: [
      "Finn! Você conseguiu… O Enchiridion, depois de tantos e tantos anos.",
      "Deixe este velho herói segurá-lo. Só um instante… por favor.",
    ],
    morph: "O Billy… está se desfazendo!",
    reveal: [
      "Hmm… ha… ha… ha…",
      "Billy? Não, criança. O Billy morreu no dia em que eu saí do âmbar. Eu só vesti o que sobrou dele.",
      "Eu sou o Lich.",
      "Eu precisava de um herói de verdade: alguém que vencesse os chefes, juntasse os três diamantes e todos os cristais de Ooo… e abrisse este templo para mim.",
      "E você foi perfeito, Finn. Obrigado.",
      "Com o Enchiridion, eu abro o caminho para a minha dimensão. E de lá, toda a vida de Ooo vai se apagar.",
      "Siga-me, se tiver coragem… pequeno herói.",
    ],
    portal: "O <b>Lich</b> estava no corpo do <b>Billy</b> esse tempo todo! Ele fugiu com o <b>Enchiridion</b> por um <b>portal sombrio</b>, na frente do templo. Entre nele!",
    enter: "Você atravessou o portal para a <b>dimensão do Lich</b>: uma caverna de montanhas de ossos. Ele espera no meio dela.",
    back: "De volta à <b>Caverna dos Ossos</b>. O portal atrás de você leva de volta ao templo.",
    // talking to him in his cave: the first time (then the fight), and after Finn fainted (a rematch)
    cave: [
      "Então você veio. Corajoso… e tolo.",
      "Bem-vindo à minha caverna. Cada osso aqui foi um herói que também achou que podia me deter.",
      "O Enchiridion já é meu. Olhe bem para o seu Billy, Finn: é assim que terminam todos os heróis.",
      "Chega de conversa. Venha, criança… e caia como todos os outros.",
    ],
    again: [
      "Você voltou. Os ossos daqui adoram visitas.",
      "Ainda de pé? Vamos resolver isso.",
      "Toda vida acaba, Finn. A sua primeiro.",
      "Mais uma vez, então. Eu tenho toda a eternidade.",
    ],
    // after he lost: his echo, a flicker of green fire on the heap (talk twice: a rematch)
    echo: [
      "…eu… sou… o fim…",
      "Nenhum livro me prende para sempre, criança. Eu sou uma roda que sempre volta.",
      "Quer me ver cair de novo? Fale comigo outra vez… se tiver coragem.",
    ],
    echoFight: "Então venha. Desta vez, eu não caio.",
    // the fight (lichboss.js)
    boss: ["O Lich", "O Lich"],
    phase: [["No corpo do Billy", "No corpo do Billy · fúria", "No corpo do Billy · Fogo Verde"], ["Forma verdadeira", "Forma verdadeira · fúria", "Forma verdadeira · CAIA"]],
    cast: {
      claw: "Garras do Lich", kick: "Chute do Herói", quake: "Salto da Tumba", spikes: "Ossos da Terra", bolt: "Chamas Verdes",
      inferno: "Fogo Verde dos Mortos", counter: "Fúria da Morte",
      orbs: "Chamas da Morte", breath: "Sopro da Morte", stop: "Pare", raise: "Necromancia", blackfire: "Fogo Negro",
      comet: "Cometa Catalisador", sweep: "Relâmpago Verde", fall: "Caia", dark: "Explosão Sombria",
    },
    shout: {
      claw: ["Venha cá, herói.", "Suas costas são minhas.", "Ossos quebram fácil."],
      kick: ["Lembra deste chute? Foi com ele que o Billy me derrubou.", "Um golpe de herói… para um herói."],
      quake: ["Não há onde se esconder.", "Do alto… a queda."],
      spikes: ["Levantem-se, ossos!", "A terra dos mortos te chama."],
      bolt: ["Queime.", "Fogo verde. Fogo da morte."],
      inferno: ["Que o chão inteiro queime!", "O fogo dos mortos, Finn! Suba… se puder!"],
      counter: ["Afaste-se!", "Tolo!", "Você não me toca!"],
      orbs: ["Chamas da morte.", "Arda."],
      breath: ["Respire fundo, criança.", "O mesmo sopro que calou o Prismo."],
      raise: ["Levantem-se, meus heróis caídos.", "Os mortos lutam por mim."],
      blackfire: ["O fogo negro devora tudo.", "Nada escapa do fogo negro."],
      comet: ["Eu vim do céu, Finn. Numa estrela verde.", "Veja o cometa que me trouxe."],
      sweep: ["Relâmpago!", "Dance, herói."],
    },
    stopWord: "PARE.",
    stopSay: "Pare.",
    fallWord: "CAIA.",
    fallSay: ["Você está sozinho, criança. Só existe escuridão para você.", "Eu sou o fim. E eu vim por você, Finn."],
    spent: ["Hm… ainda de pé…", "Aquela luz… o livro…"],
    intro: "Venha, pequeno herói. Mostre-me o que o Billy nunca conseguiu.",
    hurt: ["Hmph.", "Isso é tudo?", "Patético.", "Um arranhão."],
    dropped: ["Pegue. Não vai adiantar.", "Aproveite enquanto dura."],
    rage: [["Chega de brincadeira.", "Este corpo velho ainda tem fogo!"], ["Sinta o peso da eternidade!", "Toda luz… se apaga!"]],
    tear: ["Este corpo… não me serve mais.", "Veja o que existe por baixo, Finn!", "Agora você conhece o Lich de verdade."],
    defeat: ["NÃO! O que é esta luz?!", "O Enchiridion… está me puxando…"],
    finnDown: ["Caia. Como todos os outros.", "Mais um osso para a minha coleção.", "Descanse, herói. Para sempre."],
    faint: "Você desmaiou… O Jake te arrastou até a entrada da caverna. Fale com o Lich para tentar de novo.",
    healHint: "A última luta! Você <b>não se cura sozinho</b>: pegue os corações que o Lich deixa cair. Cuidado com o <b>contra-ataque</b> se bater demais de uma vez.",
    infernoHint: "O chão vai pegar fogo! Suba numa <b>montanha de caveiras</b> (as do meio da caverna) antes que ele acenda!",
    fallHint: "<b>CAIA</b> mata na hora! Corra para a <b>luz dourada do Enchiridion</b>, no monte do meio!",
    sealed: "O portal se fechou! Não há como fugir do <b>Lich</b>.",
    tearHint: "O Lich arrancou a pele do Billy! Agora ele só usa <b>magia</b>.",
    end: "<b>Você venceu o Lich!</b> O espírito dele ficou preso no Enchiridion, e o livro dos heróis voltou para as suas mãos. <b>Ooo está salva!</b> Fim da aventura… por enquanto.",
    again2: "Você venceu o Lich de novo! O Enchiridion está a salvo com você.",
    // the objective box and the journal's next step (save.lich.q)
    goal: { portal: "Entre no portal sombrio, no Templo", cave: "Derrote o Lich, na Caverna dos Ossos", won: "" },
    next: {
      none: "O Billy quer ver o Enchiridion: volte à porta do templo.",
      portal: "O Billy era o Lich! Ele fugiu com o Enchiridion por um portal sombrio, na frente do Templo do Enchiridion. Entre nele.",
      cave: "O Lich está com o Enchiridion, no meio da Caverna dos Ossos: fale com ele para lutar. O portal dele fica na frente do Templo do Enchiridion.",
      won: "Você venceu o Lich e recuperou o Enchiridion. Ooo está salva! (O eco dele ainda assombra a caverna, para quem quiser a revanche.)",
    },
  },
  jake: {
    lichReveal: "Mano… o Billy era o LICH esse tempo todo?! Que nojento! Bora atrás dele!",
    lichCave: "Uou… é tudo osso, mano. Montanhas de caveiras! Fica pertinho de mim.",
    lichFight: "É agora, mano! A última luta! Eu tô contigo até o fim!",
    lichInferno: "Mano! Sobe nas montanhas de caveira, rápido!",
    lichFall: "CORRE PRO LIVRO, FINN! Pra luz dourada!",
    lichTear: "Eca! Ele tirou o Billy igual uma meia velha!",
    lichWin: "VOCÊ VENCEU O LICH, MANO! Você é o maior herói de Ooo! Mais que o Billy!",
    lichRetry: "Relaxa, mano. A gente respira e volta. Fala com ele quando quiser.",
    crystals: "Mano, os diamantes e os cristais! Tudo! Bora pro templo, a leste de casa. O Billy tá esperando lá!",
    billyLeap: "Uou! Ele pulou até as nuvens, mano! Com essa idade!",
    templeOpen: "Uou, a porta abriu sozinha! Tem alguma coisa brilhando lá dentro, mano!",
    book: "O Enchiridion, mano! O livro dos heróis de verdade! Você é o cara!",
    arena: "Eu te ajudo, mano! Estiquei até aqui em cima!",
    bossWin: "Você derrubou a coroa dele, mano! Algébrico!",
    retry: "Levanta, mano! Bora de novo, a gente pega ele!",
    lair: "Que lugar sinistro, mano! Mas eu tô contigo!",
    lairWin: "Você venceu o Mordomo Menta, mano! E que espada irada!",
    lairRetry: "Relaxa, mano. Fala com ele de novo quando quiser a revanche.",
    colosseum: "Um coliseu de fogo, mano?! Que calor! Bora pra cima dele!",
    colWin: "Você venceu o Rei de Fogo, mano! Matemático!",
    colRetry: "Relaxa, mano. Fala com a Princesa de Fogo quando quiser tentar de novo.",
    pillars: "Mano! Atrás das colunas, rápido!",
    hurry: "Corre, mano! A chama tá apagando!",
    first: "Matemático! Nosso primeiro cristal!",
    collect: ["Algébrico!", "Matemático!", "Mais um pra coleção, mano!", "Isso aí, Finn!"],
    hurt: ["Ai! Cuidado, cara!", "Ô, essa doeu!"],
    lava: "Tá quente! Tá quente!",
    fainted: "Relaxa, mano, eu te levo pra casa.",
    wait: "Vou esperar aqui embaixo, mano!",
    punch: ["Toma essa, gosma!", "Soco esticado!", "Braço de borracha!", "Pou!"],
    slam: ["Punho gigante!", "Hora do tamanho família!", "Sai da frente, gosmada!"],
    recharge: "Peraí, mano, tô recarregando o punho!",
    fireFirst: "Mano! Você solta fogo pela espada agora?! Que algébrico!",
    fire: ["Onda de fogo, mano!", "Queima, gosmada!", "Uou, que quentura!"],
    win: "Você é o herói mais matemático de Ooo!",
  },
};
